// <auto-generated />
using Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250310192138_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Api.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "samsung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "iphone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "huawei"
                        },
                        new
                        {
                            Id = 5,
                            Name = "nokia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "lg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "sony"
                        },
                        new
                        {
                            Id = 8,
                            Name = "motorola"
                        });
                });

            modelBuilder.Entity("Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Api.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "white"
                        },
                        new
                        {
                            Id = 3,
                            Name = "blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "gray"
                        },
                        new
                        {
                            Id = 5,
                            Name = "gold"
                        });
                });

            modelBuilder.Entity("Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("PhoneId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Api.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "galaxy s23"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "galaxy note 20"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "galaxy z fold 4"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "iphone 14"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Name = "iphone 13"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "iphone 12"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            Name = "mi 11"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Name = "redmi note 10"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Name = "poco f4"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 4,
                            Name = "p40 pro"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            Name = "mate 40 pro"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            Name = "p30 lite"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 5,
                            Name = "nokia 8.3"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 5,
                            Name = "nokia 7.2"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            Name = "nokia 5.4"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 6,
                            Name = "lg velvet"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 6,
                            Name = "lg v60 thinq"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 6,
                            Name = "lg g8x thinq"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 7,
                            Name = "sony xperia 1 ii"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 7,
                            Name = "sony xperia 10 ii"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 7,
                            Name = "sony xperia l4"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 8,
                            Name = "moto g power"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 8,
                            Name = "moto edge 20"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 8,
                            Name = "moto e 2020"
                        });
                });

            modelBuilder.Entity("Api.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ColorId = 1,
                            ModelId = 1,
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            ColorId = 2,
                            ModelId = 2,
                            Price = 600m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            ColorId = 3,
                            ModelId = 3,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ColorId = 4,
                            ModelId = 4,
                            Price = 1000m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            ColorId = 5,
                            ModelId = 5,
                            Price = 800m
                        });
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoneUser", b =>
                {
                    b.Property<int>("LikedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikedPhonesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LikedById", "LikedPhonesId");

                    b.HasIndex("LikedPhonesId");

                    b.ToTable("PhoneUser");
                });

            modelBuilder.Entity("Api.Models.Cart", b =>
                {
                    b.HasOne("Api.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Api.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Item", b =>
                {
                    b.HasOne("Api.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Phone", "Phone")
                        .WithMany("Items")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Api.Models.Model", b =>
                {
                    b.HasOne("Api.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Api.Models.Phone", b =>
                {
                    b.HasOne("Api.Models.Brand", "Brand")
                        .WithMany("Phones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Color", "Color")
                        .WithMany("Phones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Model", "Model")
                        .WithMany("Phones")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("PhoneUser", b =>
                {
                    b.HasOne("Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Phone", null)
                        .WithMany()
                        .HasForeignKey("LikedPhonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Brand", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Api.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Api.Models.Color", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Api.Models.Model", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Api.Models.Phone", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
